{% set name = "txl-console" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_console-{{ version }}.tar.gz
  sha256: 585fb7ef1df9feec44ec66edbd7de588d69e9bad2597f373f611797905c47cee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - jupyter_ydoc >=2.0.0,<3.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_console

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  summary: TXL plugin for a Jupyter console
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
