{% set python_min = "3.10" %}
{% set name = "txl-console" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_console-{{ version }}.tar.gz
  sha256: e977532ca25fb3eb454aa733c25b5b0d3b1c33437042647b6d2b7698ccf34bd9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - jupyter_ydoc >=3.0.2,<4.0.0

test:
  requires:
    - pip
  commands:
    - pip check
    - python {{ python_min }}
  imports:
    - txl_console

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  summary: TXL plugin for a Jupyter console
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
