{% set name = "txl-console" %}
{% set version = "0.2.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_console-{{ version }}.tar.gz
  sha256: 53db18542e67b6e9dbcc602c5c842a068d56d8d5d14ae75a8ac6d419c66d1bd9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0
    - jupyter_ydoc >=3.0.2,<4.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_console

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  summary: TXL plugin for a Jupyter console
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/console
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
